### ISSUE TITLE
ZFS version check fails if letters are present in the version number

### ISSUE THREAD

**Issue by iamoptimans** [optimans/cockpit-zfs-manager#1]
Proxmox VE 6.0

cat /sys/module/zfs/version displays: 0.8.2-pve2

![Proxmox VE 6 0 ZFS](https://user-images.githubusercontent.com/58222345/69864841-cc6baa80-12da-11ea-81b7-7e0dc14661ff.png)

Credits to EluRex for finding this

**Comment by seffyroff** [comment]
Seeing the same on Ubuntu 19.10:
seffyroff@ame:~/dev/cockpit-zfs-manager$ modinfo zfs
filename:       /lib/modules/5.3.0-24-generic/kernel/zfs/zfs.ko
version:        0.8.1-1ubuntu14
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
alias:          devname:zfs
alias:          char-major-10-249
srcversion:     A253AC98C8B411B821150CC
depends:        zlua,spl,znvpair,zcommon,icp,zunicode,zavl
retpoline:      Y
name:           zfs

seffyroff@ame:~/dev/cockpit-zfs-manager$ cat /sys/module/zfs/version
0.8.1-1ubuntu14

**Comment by iamoptimans** [comment]
Hi seffyroff,

Can you please post more information about your system eg: fresh install, upgrade. Are you suffering from the /bin /usr/bin issue like with Proxmox VE 5 -> 6 upgrade #2 ?

I have typed both 0.8.1-1ubuntu14 and 0.8.2-pve2 into the version check and both work.

Fresh install of Ubuntu 19.10 works with default install too:

![image](https://user-images.githubusercontent.com/58222345/70026977-f9220980-15db-11ea-9e94-4f1c79290795.png)

If the returned value is all letters, it will allow you to continue, I'm thinking the error is with the cat command.

Can you please also post a screenshot of the console logging?

Thanks

**Comment by iamoptimans** [comment]
Improved the handling of the version check and will correctly detect version number with 0.1.1.158 release.
