### ISSUE TITLE
Support for cockpit 221

### ISSUE THREAD

**Issue by hans00** [optimans/cockpit-zfs-manager#11]
The version 221 removed the patternfly.css.

https://github.com/cockpit-project/cockpit/pull/14105

**Comment by iamoptimans** [comment]
Hi @hans00,

Sorry for late reply, thanks for the heads up. Working on it and should have update out very shortly

**Comment by iamoptimans** [comment]
Hi @hans00,

0.3.2.348 is available. Can you please test to make sure all is OK?

I have tested changes  on builds from 201 - 221.

Thanks

**Comment by hans00** [comment]
Thanks for fixing.

I have tested, all are OK.
