### ISSUE TITLE
Why do datasets that have samba sharing enabled show up twice in Windows Explorer?

### ISSUE THREAD

**Issue by UntouchedWagons** [optimans/cockpit-zfs-manager#12]
I'm trying out Cockpit in a VM with your project installed. I created a dataset and enabled Samba shares and when I go browse shares in Windows Explorer that share shows up twice. Once because the dataset's sharesmb property is enabled and a second time because it's explicitly shared through samba. I'm wondering what the reasoning is for this?

**Comment by iamoptimans** [comment]
Hi @UntouchedWagons,

Have you got usershares enabled in your Samba configuration? This is one of the caveats of using CZM and ZFS on Linux:

[https://github.com/optimans/cockpit-zfs-manager#samba-1](https://github.com/optimans/cockpit-zfs-manager#samba-1)

> **Samba**
>
> ZFS always creates shares in /var/lib/samba/usershares folder when ShareSMB property is enabled. This is also the case even if Cockpit ZFS Manager is managing the shares. To avoid duplicate shares of the same file system, it is recommended to configure a different usershares folder path if required or to disable usershares in the Samba configuration file.
> 
> If enabled, Cockpit ZFS Manager manages shares for the file systems only. Samba global configuration will need to be configured externally.

Next version will have enhancement to detect if usershares is enabled whilst CZM is managing shares.

**Comment by UntouchedWagons** [comment]
No, actually. I have user shares disabled. My smb.conf file is pretty barebones:

    [global]
    workgroup = WORKGROUP
    server string = %h server (Samba, Ubuntu)
    log file = /var/log/samba/log.%m
    max log size = 1000
    logging = file
    panic action = /usr/share/samba/panic-action %d
    server role = standalone server
    obey pam restrictions = yes
    unix password sync = yes
    passwd program = /usr/bin/passwd %u
    passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
    pam password change = yes
    map to guest = bad user
    usershare allow guests = yes

    # COCKPIT ZFS MANAGER
    # WARNING: DO NOT EDIT, AUTO-GENERATED CONFIGURATION
    include = /etc/cockpit/zfs/shares.conf
    include = /run/cockpit/zfs/shares.conf

**Comment by schopenhauer** [comment]
Could it be a simple duplicate entry of `include = /etc/cockpit/zfs/shares.conf` at the end of the smb.conf file?

**Comment by UntouchedWagons** [comment]
I didn't put those two entries in smb.conf, and they're not duplicates.

**Comment by iamoptimans** [comment]
The additions to smb.conf look correct. I see there is _usershare allow guests_ but don't think it is [the issue](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html).

Are you able to send me some command outputs, to see where the duplicate is shown (Redact if needed, or send me a PM):

`# tree /etc/cockpit/zfs`
`# cat /etc/cockpit/zfs/*.conf`

@schopenhauer, The conf files stored in /run are for temporary storage pool imports - read only and/or altroot defined.

> include = /etc/cockpit/zfs/shares.conf
include = /run/cockpit/zfs/shares.conf

**Comment by UntouchedWagons** [comment]
root@storage-test:~# tree /etc/cockpit/zfs
    /etc/cockpit/zfs
    ├── config.json
    ├── shares
    │   ├── media_Backups.conf
    │   └── media_Videos.conf
    ├── shares.conf
    └── snapshots

    2 directories, 4 files
    root@storage-test:~# cat /etc/cockpit/zfs/*.conf
    # COCKPIT ZFS MANAGER
    # WARNING: DO NOT EDIT, AUTO-GENERATED CONFIGURATION
    include = /etc/cockpit/zfs/shares/media_Backups.conf
    include = /etc/cockpit/zfs/shares/media_Videos.conf

**Comment by iamoptimans** [comment]
@UntouchedWagons, thanks for the output, can you please run this command as well?

`# cat /etc/cockpit/zfs/shares/*.conf`

**Comment by UntouchedWagons** [comment]
# cat /etc/cockpit/zfs/shares/*.conf
    # COCKPIT ZFS MANAGER
    # WARNING: DO NOT EDIT, AUTO-GENERATED CONFIGURATION
    [Backups]
            path = /media/Backups
            comment = ZFS: media/Backups
            browseable = yes
            read only = no
            guest ok = no

    # ADD ADDITIONAL CONFIGURATION HERE

    # COCKPIT ZFS MANAGER
    # WARNING: DO NOT EDIT, AUTO-GENERATED CONFIGURATION
    [Videos]
            path = /media/Videos
            comment = ZFS: media/Videos
            browseable = yes
            read only = no
            guest ok = no

    # ADD ADDITIONAL CONFIGURATION HERE

**Comment by iamoptimans** [comment]
Thanks again for the output.

Shares configuration looks good. The share names are unique.

With the duplicate shares in Windows Explorer, is it the same for both Backups and Videos? (Does it show the duplicate as media_Backups and media_Videos?)

**Comment by UntouchedWagons** [comment]
Yes that's correct.

**Comment by iamoptimans** [comment]
Ok, can you try these commands please?

` # ls -alF /var/lib/samba/usershares`
`# smbstatus --shares`
`# smbclient -L localhost`

**Comment by UntouchedWagons** [comment]
root@storage-test:~# ls -alF /var/lib/samba/usershares
    total 16
    drwxrwx--T 2 root sambashare 4096 Aug  3 01:50 ./
    drwxr-xr-x 7 root root       4096 Aug  3 01:49 ../
    -rw-r--r-- 1 root root        122 Aug  3 01:50 media_backups
    -rw-r--r-- 1 root root        119 Aug  3 01:50 media_videos
    root@storage-test:~# smbstatus --shares

    Service      pid     Machine       Connected at                     Encryption   Signing
    ---------------------------------------------------------------------------------------------

    root@storage-test:~# smbclient -L localhost -U UntouchedWagons
    Enter WORKGROUP\UntouchedWagons's password:

            Sharename       Type      Comment
            ---------       ----      -------
            Backups         Disk      ZFS: media/Backups
            Videos          Disk      ZFS: media/Videos
            IPC$            IPC       IPC Service (storage-test server (Samba, Ubuntu))
            media_Videos    Disk      Comment: /media/Videos
            media_Backups   Disk      Comment: /media/Backups
    SMB1 disabled -- no workgroup available

**Comment by iamoptimans** [comment]
Ok, so for some reason, the configurations in the usershares folder are being added as well.

I wonder if the _usershare allow guests = yes_ is the culprit. Can you please comment out this line and restart samba or reboot the server if possible.

Thanks

**Comment by UntouchedWagons** [comment]
I removed `usershare allow guests = yes` and restarted the server, the extra shares still show up because the datasets' sharesmb property gets enabled when samba shares are turned on.

**Comment by iamoptimans** [comment]
Yes, you are correct, ZFS auto creates a conf in the /var/lib/samba/usershares when importing the storage pools. Usually by disabling the usershares in smb.conf, Samba will ignore the folder.

Can you please try:
`# mkdir /var/lib/samba/usershares2`

add the following to smb.conf
`usershare path = /var/lib/samba/usershares2`

Restart Samba, hoping this will fix

**Comment by UntouchedWagons** [comment]
That did the trick, but I still don't understand what causes the dataset's sharesmb property to be toggled to on. Surely not toggling that property is the better solution?

**Comment by iamoptimans** [comment]
Awesome!

I wonder if the usershares is now enabled by default with newer Samba versions. I will have a look at the documentation and see if there were any changes made.

Are you running Ubuntu 20.04?

Can you please restart the server to make sure this change is permanent; ZFS will re-create those conf files on boot, just want to make sure Samba will ignore.

**Comment by UntouchedWagons** [comment]
Yeah the duplicate shares don't show up after a reboot and yes I'm running Ubuntu 20.04.

**Comment by iamoptimans** [comment]
👍 

Will have a look at the Samba docs and update the Samba caveats section.

Think I will make an enhancement to the welcome wizard to sort this out as well.

Thanks for your help
