### ISSUE TITLE
Automatic detection of block size (e.g. ashift=12 for 4K drives)

### ISSUE THREAD

**Issue by schopenhauer** [optimans/cockpit-zfs-manager#14]
I run an array of 6x WD Red NAS (2 TB) drives, which have a physical block size of 4KB. When creating a new pool, I selected the "Auto Detect" option, i.e. not explicitly selecting any specific block size for the ZFS pool.

However, the wizard chose the default value of 512 bytes, when in fact 4KB would have been more appropriate for my drives. The physical block size of 4K was also correctly shown in the drive list, so I didn't bother to make the explicit choice.

Could you please look into the "Auto Detect" functionality, which might not work properly, at least for WD Red NAS drives?

**Comment by iamoptimans** [comment]
Hi @schopenhauer,

I have had a look at the code, and auto detect sets option ashift=0 on create. ZFS gets the sector sizes from the kernel, CZM doesn't have control of this. Is the MIN-IO being reported as 4096 for your disks?

`# lsblk -o name,min-io,log-sec,phy-sec`

Are you able to re-create your storage pool again with forced sector size to 4 KiB?

![image](https://user-images.githubusercontent.com/58222345/89168323-47ded380-d5af-11ea-879c-551a63c87ccc.png)

**Comment by schopenhauer** [comment]
Indeed, this is what I've done. I recreated a new pool, where I manually set ashift to 12. Here is the output from `lsblk -o name,min-io,log-sec,phy-sec` with my current pool configuration:

```
NAME                          MIN-IO LOG-SEC PHY-SEC
sda                             4096     512    4096
├─sda1                          4096     512    4096
└─sda9                          4096     512    4096
sdb                             4096     512    4096
├─sdb1                          4096     512    4096
└─sdb9                          4096     512    4096
sdc                             4096     512    4096
├─sdc1                          4096     512    4096
└─sdc9                          4096     512    4096
sdd                             4096     512    4096
├─sdd1                          4096     512    4096
└─sdd9                          4096     512    4096
sde                             4096     512    4096
├─sde1                          4096     512    4096
└─sde9                          4096     512    4096
sdf                             4096     512    4096
├─sdf1                          4096     512    4096
└─sdf9                          4096     512    4096
sdg                             4096     512    4096
└─sdg1                          4096     512    4096
```

**Comment by iamoptimans** [comment]
I did some testing to be sure and can confirm that ashift=0 is being passed through when using auto detect.

![image](https://user-images.githubusercontent.com/58222345/89252638-e66d4200-d64c-11ea-8b23-9047a2709ae0.png)

ZFS documentation shows:
> Values from 9 to 16, inclusive, are valid; also, the value 0 (the default) means to auto-detect using the kernel's block layer and a ZFS internal exception list.

With your MIN-IO being 4096 you think it would of set the sector size to 4 KiB. Does not guarantee it will though.

For next version, I can change the dropdown to 4 KiB as the default option, since nearly all drives are now 4K capable, and have an inline alert when auto detect is selected to state that auto detect does not guarantee correct sector size will be chosen by ZFS.

**Comment by schopenhauer** [comment]
Ok, thank you for checking this issue. Indeed, a sector size of 4KiB should be a good default option nowadays.
