### ISSUE TITLE
When you create a File System it the selinux context is always set to system_u:object_r:samba_share_t:s0

### ISSUE THREAD

**Issue by brourk** [optimans/cockpit-zfs-manager#15]
I can create a storage pool with or without the selinux context being set.   But when I create a File System the selinux context is always set to system_u:object_r:samba_share_t:s0 regardless of the SELinux contexts for Samba setting.

**Comment by iamoptimans** [comment]
Hi @brourk,

0.3.3 is now available, which should solve this bug.

Thanks
