### ISSUE TITLE
Create a new pool with extended attributes

### ISSUE THREAD

**Issue by schopenhauer** [optimans/cockpit-zfs-manager#17]
it would be nice to add the possibility to set the `xattr=sa` flag when creating a new pool

**Comment by iamoptimans** [comment]
Hi @schopenhauer,

Newly created storage pools have the following defaults:

[Caveats:](https://github.com/optimans/cockpit-zfs-manager#caveats)

> **Storage Pools**
> New storage pools are created with the following properties set (not visible in Create Storage Pool modal):
> 
> - aclinherit=passthrough
> - acltype=posixacl
> - casesensitivity=sensitive
> - normalization=formD
> - sharenfs=off
> - sharesmb=off
> - utf8only=on
> - xattr=sa

Can also be set after creation.

Next version, the create modal will be changed to a wizard that will allow more configurable options to be displayed including this one.
