### ISSUE TITLE
New feature request: Add and remove cache devices to pools

### ISSUE THREAD

**Issue by schopenhauer** [optimans/cockpit-zfs-manager#18]
It would be nice to have the functionality to add and remove read / L2ARC (`zpool pool1 tank cache ... `) or write / SLOG (`zpool add pool1 log ...`) cache devices to existing pools (or potentially new pools upon creation of these).

**Comment by iamoptimans** [comment]
Hi schopenhauer,

You can add virtual devices from the status tab of your storage pool. Use the actions menu for your storage pool and select Add Virtual Device:

![image](https://user-images.githubusercontent.com/58222345/93155979-cb0c5100-f739-11ea-99b8-795c5a196004.png)

Here you can select which type you want. Note, options will only be displayed if @feature is enabled for the storage pool (eg Special).

![image](https://user-images.githubusercontent.com/58222345/93155999-d0699b80-f739-11ea-9cb4-3f0daebdf5e6.png)

Use the actions menu for the virtual device you want to remove. Note, remove virtual device will only appear if the @feature is enabled and there are more than 1 virtual devices added to your storage pool.

**Comment by schopenhauer** [comment]
Ok, thank you for the clarification. In this case, I believe this "issue" can be closed?
