### ISSUE TITLE
dataset properties and samba

### ISSUE THREAD

**Issue by gnordli** [optimans/cockpit-zfs-manager#19]
Hi.

Are these the suggested  properties for Samba now? 

```
    casesensitivity=sensitive
    normalization=formD
    utf8only=on
```

I didn't even know they existed until I saw them listed here.  In the past I have used case sensitivity = mixed. 

thanks,
Geoff

**Comment by iamoptimans** [comment]
Hi Geoff,

Case sensitivity = sensitive is the default value. It is currently hard set at creation. These settings were copied from Napp-IT, to keep the same, in case the user switches between OS. When version 1.0 is released, the user will have the option to select at storage pool creation.

With normalization, there is a lot of information out there to read, but seems to be best case for mixed OS sharing. UTF8Only is forced on when normalization != none.

Hope this helps.

**Comment by iamoptimans** [comment]
Forgot to mention; the case sensitivity can currently be selected when creating a child file system.

I use case insensitive for my Windows environment.

**Comment by gnordli** [comment]
Hi @iamoptimans 

Thanks for the feedback.  That makes sense. 

Geoff
