### ISSUE TITLE
Proxmox VE 6.0 bin folder is in different location

### ISSUE THREAD

**Issue by iamoptimans** [optimans/cockpit-zfs-manager#2]
Proxmox VE 6.0

zfs.js calls

- /usr/bin/cat
- /usr/bin/grep
- /usr/bin/echo

but Proxmox bin directory is at

- /bin/cat
- /bin/grep
- /bin/echo

ln -s to make then works

Credits to EluRex for finding this

**Comment by elurex** [comment]
installation method to get zfs manager to work under PVE 6.0

`echo "deb http://deb.debian.org/debian buster-backports main" > /etc/apt/sources.list.d/buster-backport.list;
apt update;
apt-get -t buster-backports install cockpit;
git clone https://github.com/cockpit-project/cockpit;
cp -r cockpit/zfs /usr/share/cockpit;

systemctl enable cockpit.service;
systemctl start cockpit.service;

#for pve5to6
ln -s /bin/cat /usr/bin/cat;
ln -s /bin/grep /usr/bin/grep;
ln -s /bin/echo /usr/bin/echo;
ln -s /bin/lsblk /usr/bin/lsblk;`

**Comment by iamoptimans** [comment]
Tested for absolute path locations on various distributions as per tables below. Was able to find matches for all commands except for zgenhostid (Debian), which there is code to make adjustments for the path location.

**Symbolic links should no longer be required for older/upgraded distributions.**


Forcing Paths for ZFS.js and shell

<table>
<tbody>
<tr>
<td width="95">&nbsp;</td>
<td width="77">
<p>CentOS 8.0</p>
</td>
<td width="77">
<p>Proxmox VE 5.4</p>
</td>
<td width="77">
<p>Ubuntu 19.10</p>
</td>
<td width="77">
<p>Debian 10.0</p>
</td>
<td width="77">
<p>Debian 9.8</p>
</td>
<td width="76">
<p>Proxmox VE 6.0</p>
</td>
<td width="76">
<p>Ubuntu 18.04</p>
</td>
<td width="72">
<p>Arch Linux 2019.10</p>
</td>
</tr>
<tr>
<td width="95">
<p>awk</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="76">
<p>/usr/bin</p>
</td>
<td width="76">
<p>/usr/bin</p>
</td>
<td width="72">
<p>/usr/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>blkid</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="76">
<p>/sbin</p>
</td>
<td width="76">
<p>/sbin</p>
</td>
<td width="72">
<p>/sbin</p>
</td>
</tr>
<tr>
<td width="95">
<p>cat</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>date</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>echo</p>
</td>
<td width="77">
<p>/bin *</p>
</td>
<td width="77">
<p>/bin *</p>
</td>
<td width="77">
<p>/bin *</p>
</td>
<td width="77">
<p>/bin *</p>
</td>
<td width="77">
<p>/bin *</p>
</td>
<td width="76">
<p>/bin *</p>
</td>
<td width="76">
<p>/bin *</p>
</td>
<td width="72">
<p>/bin *</p>
</td>
</tr>
<tr>
<td width="95">
<p>grep</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>hostnamectl</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="76">
<p>/usr/bin</p>
</td>
<td width="76">
<p>/usr/bin</p>
</td>
<td width="72">
<p>/usr/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>ls</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>lsblk</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>mkdir</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>mv</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>nfsstat</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="76">
<p>/usr/sbin</p>
</td>
<td width="76">&nbsp;</td>
<td width="72">
<p>/usr/sbin</p>
</td>
</tr>
<tr>
<td width="95">
<p>printf</p>
</td>
<td width="77">
<p>/usr/bin *</p>
</td>
<td width="77">
<p>/usr/bin *</p>
</td>
<td width="77">
<p>/usr/bin *</p>
</td>
<td width="77">
<p>/usr/bin *</p>
</td>
<td width="77">
<p>/usr/bin *</p>
</td>
<td width="76">
<p>/usr/bin *</p>
</td>
<td width="76">
<p>/usr/bin *</p>
</td>
<td width="72">
<p>/usr/bin *</p>
</td>
</tr>
<tr>
<td width="95">
<p>rm</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>sed</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>smbcontrol</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">&nbsp;</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="76">&nbsp;</td>
<td width="76">
<p>/usr/bin</p>
</td>
<td width="72">
<p>/usr/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>smbd</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">&nbsp;</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="76">&nbsp;</td>
<td width="76">
<p>/usr/sbin</p>
</td>
<td width="72">
<p>/usr/sbin</p>
</td>
</tr>
<tr>
<td width="95">
<p>systemctl</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="77">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="76">
<p>/bin</p>
</td>
<td width="72">
<p>/bin</p>
</td>
</tr>
<tr>
<td width="95">
<p>zfs</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="76">
<p>/sbin</p>
</td>
<td width="76">
<p>/sbin</p>
</td>
<td width="72">&nbsp;</td>
</tr>
<tr>
<td width="95">
<p>zgenhostid</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/bin</p>
</td>
<td width="77">
<p>/usr/sbin</p>
</td>
<td width="77">&nbsp;</td>
<td width="76">
<p>/usr/bin</p>
</td>
<td width="76">
<p>/usr/bin</p>
</td>
<td width="72">&nbsp;</td>
</tr>
<tr>
<td width="95">
<p>zpool</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="77">
<p>/sbin</p>
</td>
<td width="76">
<p>/sbin</p>
</td>
<td width="76">
<p>/sbin</p>
</td>
<td width="72">&nbsp;</td>
</tr>
</tbody>
</table>

\* Shell builtin &ndash; does not require full path

Requires full path in shell

<table width="0">
<tbody>
<tr>
<td width="97">&nbsp;</td>
<td width="73">
<p>CentOS 8.0</p>
</td>
<td width="76">
<p>Proxmox VE 5.4</p>
</td>
<td width="75">
<p>Ubuntu 19.10</p>
</td>
<td width="75">
<p>Debian 10.0</p>
</td>
<td width="75">
<p>Debian 9.8</p>
</td>
<td width="76">
<p>Proxmox VE 6.0</p>
</td>
<td width="75">
<p>Ubuntu 18.04</p>
</td>
<td width="75">
<p>Arch Linux 2019.10</p>
</td>
</tr>
<tr>
<td width="97">
<p>awk</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>blkid</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>cat</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>date</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>echo</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>grep</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>hostnamectl</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>ls</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>lsblk</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>mkdir</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>mv</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>nfsstat</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>printf</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>rm</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>sed</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>smbcontrol</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">&nbsp;</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">&nbsp;</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>smbd</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">&nbsp;</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="76">&nbsp;</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>systemctl</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
</tr>
<tr>
<td width="97">
<p>zfs</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
</tr>
<tr>
<td width="97">
<p>zgenhostid</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
</tr>
<tr>
<td width="97">
<p>zpool</p>
</td>
<td width="73">
<p>N</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="75">
<p>Y</p>
</td>
<td width="76">
<p>N</p>
</td>
<td width="75">
<p>N</p>
</td>
<td width="75">
<p>Y</p>
</td>
</tr>
</tbody>
</table>

<table width="0">
<tbody>
<tr>
<td width="124">&nbsp;</td>
<td width="149">
<p>ZFS.js updated</p>
</td>
<td width="124">
<p>Forced Path</p>
</td>
</tr>
<tr>
<td width="124">
<p>awk</p>
</td>
<td width="149">
<p>N</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>blkid</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>cat</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>date</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>echo</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>N</p>
</td>
</tr>
<tr>
<td width="124">
<p>grep</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>hostnamectl</p>
</td>
<td width="149">
<p>N</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>ls</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>lsblk</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>mkdir</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>mv</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>nfsstat</p>
</td>
<td width="149">
<p>N</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>printf</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>N</p>
</td>
</tr>
<tr>
<td width="124">
<p>rm</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>sed</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>smbcontrol</p>
</td>
<td width="149">
<p>N</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>smbd</p>
</td>
<td width="149">
<p>N</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>systemctl</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>zfs</p>
</td>
<td width="149">
<p>N</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>zgenhostid</p>
</td>
<td width="149">
<p>Y</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
<tr>
<td width="124">
<p>zpool</p>
</td>
<td width="149">
<p>N</p>
</td>
<td width="124">
<p>Y</p>
</td>
</tr>
</tbody>
</table>
