### ISSUE TITLE
FYI only - Updating Cockpit ZFS plugin fixed the red "Ooops" error for me

### ISSUE THREAD

**Issue by digitalformula** [optimans/cockpit-zfs-manager#21]
Hi team - sorry for logging this an issue but I'm not sure how else to do this.

I've been having that issue where Cockpit UI on CentOS 8 would throw the red "Ooops" error.  It was only since I did a package update on my main server - everything was fine until then.  In my case, the issue occurred 100% of the time when trying to use the [Cockpit ZFS](https://github.com/optimans/cockpit-zfs-manager.git) plugin.

I removed and reinstalled Cockpit, but it turns out the plugin itself needed to be updated.

```
# breaking this command into 2 lines to reduce chance of accidentally deleting /usr/share/cockpit
cd /usr/share/cockpit
sudo rm -Rf ./zfs
cd ~
# install git if you don't have it
# sudo dnf -y install git
git clone https://github.com/optimans/cockpit-zfs-manager.git
sudo cp -r cockpit-zfs-manager/zfs /usr/share/cockpit
```

Problem solved - ZFS plugin all up and running as it should.

Still have an issue where Cockpit randomly shows just a white screen, but I don't think it is related to this.

**Comment by iamoptimans** [comment]
Hi Chris,

Thanks for the feedback.

What version were you upgrading to? 224? or 233 from COPR?
Do you remember what errors were shown in the console log?

Might seem like a silly idea; does Empty Cache and Hard Reload solve the random white screen problem?

**Comment by digitalformula** [comment]
> Hi Chris,
> 
> Thanks for the feedback.
> 
> What version were you upgrading to? 224? or 233 from COPR?
> Do you remember what errors were shown in the console log?
> 
> Might seem like a silly idea; does Empty Cache and Hard Reload solve the random white screen problem?

Ah sorry about that - I didn't provide anywhere near enough detail.  More below.  :)

The red "Ooops" was a 404 when the [ZFS plugin](https://github.com/optimans/cockpit-zfs-manager.git) was trying to load jQuery.

- I was running 227 from COPR on CentOS 8.1
- Upgraded CentOS 8 packages (standard `yum`) and that's when Cockpit and the ZFS plugin started experiencing the issues
- Removed Cockpit completely as well as the COPR yum sources, and tried to reinstall without COPR (aborted that since only 211 is available in the mainline repos)
- Re-added COPR yum sources and reinstalled Cockpit 233 from there (`cockpit-233.1-2.el8.x86_64` as I write this)
- The ZFS plugin's jQuery 404 was still occurring so I completely removed the ZFS plugin from `/usr/share/cockpit`
- Reinstalled the ZFS plugin as per the steps above and the "Ooops" problem was resolved.  I've done a few tests and everything looks good there.

I should emphasise that the ZFS plugin issues were on 227 and 233 from COPR - only upgrading the plugin itself solved that problem.  I'm sorry but I don't know what version of the plugin I was running before.

Re the white screen - unfortunately no, hard refresh and clearing cache doesn't solve that issue.  I've tried Firefox, Chrome, Brave (my main browser) and have created new profiles, too.  This PC was also rebuilt completely last night so it's about as "new" as it can get in terms of cache.  :)

**Comment by iamoptimans** [comment]
Hi Chris,

Apologies for late reply, am away at the moment :smile:

> The red "Ooops" was a 404 when the [ZFS plugin](https://github.com/optimans/cockpit-zfs-manager.git) was trying to load jQuery. By "console log" do you mean `/var/log/messages`?

I was meaning the console log in your web browser.

> * I was running a version of Cockpit older than 227 (from COPR).  I'm not sure which version, unfortunately.  The ZFS plugin was totally fine with it though.  (Is there a way of seeing which packages I had before running the `yum` updates?)

$ cockpit-bridge --version (Or clicking the help link in Cockpit -> About Web Console)

> * Upgraded CentOS 8 packages (standard `yum`) and that's when Cockpit and the ZFS plugin started experiencing the issues

The update to latest (233) had a spec change which longer bundled jQuery. Hence your errors. Latest patch of CZM bundles jQuery. Good thing now, is CZM is now fully independent and should not have any issues until 1.0 comes out. When 1.0 comes out (next year) it is going to be react and no jQuery.

There has been issues raised with 233 breaking lots of plugins only with COPR. Looks like merges have been committed, so those problems should be fixed, or may have already been fixed by the time you updated.

> * Removed Cockpit completely as well as the COPR yum sources, and tried to reinstall without COPR (aborted that since only 211 is available in the mainline repos)
> * Re-added COPR yum sources and reinstalled Cockpit 233 from there (`cockpit-233.1-2.el8.x86_64` as I write this)
> * The ZFS plugin's jQuery 404 was still occurring so I completely removed the ZFS plugin from `/usr/share/cockpit`
> * Reinstalled the ZFS plugin as per the steps above and the "Ooops" problem was resolved.  I've done a few tests and everything looks good there.
> 
> I should emphasise that the ZFS plugin issues were on 227 and 233 from COPR - only upgrading the plugin itself solved that problem. I'm sorry but I don't know what version of the plugin I was running before.

That's ok, anything less than 0.3.4 would of failed to run.

> Re the white screen - unfortunately no, hard refresh and clearing cache doesn't solve that issue. I've tried Firefox, Chrome, Brave (my main browser) and have created new profiles, too. This PC was also rebuilt completely last night so it's about as "new" as it can get in terms of cache. :)

You might need to raise an issue about this with the cockpit-project. Other users have reported similar issue as well. I remember seeing this on 207, and not since.
