### ISSUE TITLE
Available space (at least) displays incorrectly after autoexpansion of VDEV

### ISSUE THREAD

**Issue by wolffstarr** [optimans/cockpit-zfs-manager#26]
Pretty sure this is a bug - I haven't found anything that I could clear on CZM's side to fix it at least. I have a zpool that consists of three RAIDZ1 VDEVs (specifically, 4x 5TB, 4x8TB, and 4x10TB disks). I just replaced my 5TB disks with 12TB disks. Prior to that I had 34TB or thereabouts free. After swapping the last drive, autoexpand worked admirably, and on the CLI and in the OpenMediaVault ZFS plugin, I see 52.0T under "Available", which makes sense with an extra 21TiB being added, after overhead. However, CZM is reporting 75.04TiB free for the pool, which seems off, even though the base pool dataset seems to be displaying correctly:

![image](https://user-images.githubusercontent.com/4945910/112733819-85b2b280-8f18-11eb-87f5-a62f25a787af.png)

This is a minor issue and may be fixed in your 0.4 rewrite, but wanted to let you know that it's a thing. I'm using 0.3.4.514 currently on Debian Buster/OpenMediaVault. Please let me know if you need additional information or need me to try something and I'd be happy to get it for you.

**Comment by iamoptimans** [comment]
Hi @wolffstarr,

Are you able to provide the output for the following commands:

`$ zpool list`
`$ zfs list -o name,used,avail,refer,usedds,usedchild,usedsnap,refreserv,quota -d 0`

Thanks

**Comment by wolffstarr** [comment]
Yep, looks like it's a ZFS thing then. Sorry for the false alarm - just can't quite figure out how its getting its numbers here. My first thought was that it's not "forgetting" the 4x5TB disks that were pulled, but the math doesn't add up that way either.

```
wolfstar@nike:~$ zpool list
NAME      SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
tank      372G  63.8G   308G        -         -     7%    17%  1.00x    ONLINE  -
trinity   109T  33.8T  75.0T        -         -     1%    31%  1.00x    ONLINE  -
wolfstar@nike:~$ zfs list -o name,used,avail,refer,usedds,usedchild,usedsnap,refreserv,quota -d 0
NAME      USED  AVAIL     REFER  USEDDS  USEDCHILD  USEDSNAP  REFRESERV  QUOTA
tank     63.8G   297G       96K     96K      63.8G        0B       none   none
trinity  24.6T  52.0T      256K    256K      24.6T      128K       none   none
wolfstar@nike:~$
```

**Comment by iamoptimans** [comment]
No problem.

Had a quick look at: https://docs.oracle.com/cd/E53394_01/html/E54801/gbbym.html

It says that the zpool list FREE is referred to as the inflated disk space value which includes redundancy overhead.

RAIDZ1 uses 1 disk size for parity. 8TB (7.27TiB) + 10TB (9.09TiB + 12TB (10.91TiB) = 27.27TiB. Yours is showing 22.99TiB discrepancy between FREE and AVAIL which is pretty close to the calculation. Correct me if I'm wrong; looks like it would be the overhead.

**Comment by wolffstarr** [comment]
Could be, yeah. I've been trying to figure out SIZE being 109T as well, because I was assuming it was showing me TB instead of TiB (Silly me), at which point nothing added up - RAIDZ1 would be 24+30+36=90TB, and Raw numbers would be 32+40+48=120TB. 

 You'd think after 20 years in IT, even if most of it's been as a network guy, I'd stop thinking TB was the normal on OS outputs. :)
