### ISSUE TITLE
config assumes location of install

### ISSUE THREAD

**Issue by rbg** [optimans/cockpit-zfs-manager#3]
Since it is possible to develop and install cockpit at (for example) /usr/local/share the hard-coded location of the config.json file can cause an issue, the system was not able save at /usr/share/cockpit. 

If it is possible to configure that would be great!

**Comment by iamoptimans** [comment]
Hi rbg,

New update available: 0.1.1.158, which will now store the configuration file in /etc/cockpit/zfs with rest of the configuration files.

There is a function on launch to relocate existing configuration file if found. Hopefully no user interaction required.

Thanks for reporting this issue.
