### ISSUE TITLE
Setting Quota

### ISSUE THREAD

**Issue by mariodoebler** [optimans/cockpit-zfs-manager#4]
Hi,

first of all great work! What do you think about an option setting the quota, similar to setting refreservation? I would find it quite useful.

**Comment by iamoptimans** [comment]
Hi @mariodoebler, thanks for the great feedback!

Were you referring to the quota property itself or the user/group quota properties?

Should be able to add the quota property to the Configure File System modal without much fuss. If you are talking about user/group quotas, will require me to do some research; may need its own modal

**Comment by mariodoebler** [comment]
I was referring to the quota property itself.

**Comment by iamoptimans** [comment]
Will be added to 0.1.2 release. Hoping to get release out in February.

**Comment by iamoptimans** [comment]
0.2.0.233 is now available with this feature request.
