### ISSUE TITLE
Feature Request: Display Snapshots in Nested List/Tree View on a Per-Dataset basis

### ISSUE THREAD

**Issue by wolffstarr** [optimans/cockpit-zfs-manager#6]
I have an extensive amount of snapshots (last check had 855 of them) under a significant number of datasets (16 plus the base pool dataset). From an organizational standpoint and for my uses, the Snapshot tab is nearly useless just because of the sheer amount of data. Filtering would work, but I think it would be cleaner to handle it as either a nested list on a per-snapshot basis, or possibly simply have them on the main filesystems tab as nested lists for child objects - this would allow for sub-lists for both Snapshots and Clones.

If it were me, I'd handle it this way:

1. Leave the existing Snapshot tab alone in terms of format. Allow for sorting/filtering based on column if possible; it would be nice to see where the data hogs are amongst all snapshots as an example.
2. Create nested lists on the filesystem tab for the snapshots, then any snapshots that have clones made from them would nest under those as well. Dealing with clones could get messy, but there should be a way to display them linking back to the original snapshot and dataset.

**Comment by iamoptimans** [comment]
Hi @wolffstarr,

0.3.0.299 is now available. Snapshots are now nested together for each file system on the snapshots tab.

Currently learning and playing with React, so there will be additional needed functionality coming in the next release.

**Comment by wolffstarr** [comment]
Oh wow, yeah. I really like the total number of snapshots per dataset too; for me it gives a quick at-a-glance idea of what frequency I have configured for automatic snapshots (with my setup using zfs-auto-snapshot, any of the ones with "80" means they're doing snapshots every 15 minutes, for example, because I know the first dataset I looked at has that config.)

Appreciate the notification that it was in on a preliminary basis. If there's anything about it that you'd like me to try and mangle let me know.

**Comment by iamoptimans** [comment]
Awesome! :smile:

Are you able to send me a config of your zfs-auto-snapshot? (PM me on STH) I do plan to automate snapshots as well, but my thoughts were to automate the zfs-auto-snapshot with the UI instead of re-inventing the wheel. Would like to see how it is used in the real world? Thanks
