### ISSUE TITLE
This package requires Cockpit version 201 or later

### ISSUE THREAD

**Issue by CSnipper** [optimans/cockpit-zfs-manager#7]
I have above warning on ZFS page

My cockpit is already the newest version (213-1~bpo10+1)

**Comment by iamoptimans** [comment]
Hi @CSnipper 

Are you able to send me a screenshot of this, information about your system and how you got version 213 installed?

Cockpit itself manages the version validation; so there should be no issue for this:

![image](https://user-images.githubusercontent.com/58222345/76674048-30925000-65e6-11ea-8201-78568e37f818.png)

![image](https://user-images.githubusercontent.com/58222345/76674155-1a38c400-65e7-11ea-9578-172c35dd732b.png)

**Comment by iamoptimans** [comment]
Hi @CSnipper, how did you go with this?

**Comment by CSnipper** [comment]
Reinstalled everything in proper order :)
